"""upadted field added

Revision ID: 342a52d99602
Revises: 7b6a5294ddd9
Create Date: 2025-11-20 22:17:19.202245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '342a52d99602'
down_revision: Union[str, Sequence[str], None] = '7b6a5294ddd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Review', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('Review', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Review', 'updated_at')
    op.drop_column('Review', 'created_at')
    # ### end Alembic commands ###
