"""updating book table

Revision ID: d3911aec1c4a
Revises: 4298bab39311
Create Date: 2025-11-18 22:43:00.377386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'd3911aec1c4a'
down_revision: Union[str, Sequence[str], None] = '4298bab39311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Book', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Book', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Book', type_='foreignkey')
    op.drop_column('Book', 'user_id')
    # ### end Alembic commands ###
