"""review model has been added to the database

Revision ID: 7b6a5294ddd9
Revises: d3911aec1c4a
Create Date: 2025-11-20 21:05:28.835509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '7b6a5294ddd9'
down_revision: Union[str, Sequence[str], None] = 'd3911aec1c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('R')
    op.add_column('Review', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('Review', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False))
    op.add_column('Review', sa.Column('book_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'Review', 'Book', ['book_id'], ['id'])
    op.drop_column('Review', 'title')
    op.drop_column('Review', 'language')
    op.drop_column('Review', 'page_count')
    op.drop_column('Review', 'created_at')
    op.drop_column('Review', 'published_date')
    op.drop_column('Review', 'author')
    op.drop_column('Review', 'description')
    op.drop_column('Review', 'publisher')
    op.drop_column('Review', 'category')
    op.drop_column('Review', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Review', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Review', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Review', sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Review', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Review', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Review', sa.Column('published_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Review', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('Review', sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Review', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Review', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Review', type_='foreignkey')
    op.drop_column('Review', 'book_id')
    op.drop_column('Review', 'comment')
    op.drop_column('Review', 'rating')
    op.create_table('R',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('R_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('R_pkey'))
    )
    # ### end Alembic commands ###
